### PR TITLE
One interface method is marked obsolete on NLog 4.5, causing the software library call to fail

### PR DESCRIPTION
**Pull request by ustcltx**
image

### CODE REVIEW

**Comment by 304NotModified** [comment]
@snakefoot while overriding `Write(AsyncLogEventInfo[] logEvents)` isn't recommend anymore, it should not lead to breaking changes? Correct?

**Comment by 304NotModified** [comment]
- [ ] update nuspec

**Comment by ustcltx** [comment]
image 

image

It only happens when I update NLog to 4.5.

**Comment by snakefoot** [comment]
Think you are having a different issue than method is obsolete. As it will not cause any problems



Sent from my Samsung device


-------- Original message --------

**Comment by 304NotModified** [comment]
current test application with NLog 4.5.4 works fine by me;

See branch "nlog45-test" - diff: https://github.com/NLog/NLog.Windows.Forms/compare/nlog45-test

**Comment by 304NotModified** [comment]
checked, both NLog version use the same "strong name":

image

**Comment by 304NotModified** [comment]
@ustcltx do you have a demo case? (github repo or zip)

**Comment by 304NotModified** [comment]
I don't think this is needed and I will close this because of inactivity. 

Please let us know if this still an issue and please provide the requested info - thanks!

**Pull request closed without merging**
