### PR TITLE
Unit tests for RTB-target retention behaviour

### PR DESCRIPTION
**Pull request by mikhail-barg**
As promised, I've added more unit-tests for the v4.1 behaviour.
During tests implementation I've invented a case when the behaviour is not as expected.
Please see `ManualRegisterTestWithRetentionConfigReload()` test (it fails).

The idea is to set `MessageRetention = RichTextBoxTargetMessageRetentionStrategy.All`, log something to actual RTB, and then force config reload. This would cause target to detach from the control and then - to re-attach. On (re)attaching the target following `...Retention...All` would issue all the messages it has effectively duplicating them in the control.

I'm not sure what to do with this. Maybe keep reference to previous target RTB in a private field and don't issue re-logging messages if attaching to same form. But it looks like a dirty hack. What do you think?

### CODE REVIEW

**Comment by mikhail-barg** [comment]
Also, reloading config currently should cause re-creation of 'accessory' form. Also looks like an unintended behaviour, but probably not that bad.

**Comment by 304NotModified** [comment]
I will run the units now, and will respond on this issue today

**Comment by 304NotModified** [comment]
Thanks for the tests. 

I have a question, the duplication of the messages? Are those limited to some? I tried it with more logging, but I only see the last 11 messages?

image

**Comment by mikhail-barg** [comment]
Yes, there's a `MaxLines = 10`, see 
```c#
            var target = new RichTextBoxTarget()
            {
                FormName = "MyForm1",
                ControlName = "Control1",
                UseDefaultRowColoringRules = true,
                Layout = "${message}",
                AllowAccessoryFormCreation = false,
                MaxLines = 10,
                MessageRetention = RichTextBoxTargetMessageRetentionStrategy.All
            };
```

**Comment by mikhail-barg** [comment]
So the reproduction scenario for the issue is:

* setup logging with `MessageRetention = ...RetentionStrategy.All` and some reasonable `MaxLines`;
* have a textbox attached to target;
* log some lines (but fewer than `MaxLines`) and see they appear in control (and also stored internally);
* issue configuration reload, it would cause:
** detaching target from control in `CloseTarget()` (seems reasonable, because we don't know if the target will exist in a new config);
** attaching target to same control in `InitializeTarget()` (also reasonable);
** logging all stored messages to target (the behaviour of `RetentionStrategy.All`), which would cause the duplication because these messages are already there.

So I see the following possible solutions:
1. Don't detach from target in `CloseTarget()` and don't re-attach in `InitializeTarget()` if it's the same target, therefore the messages would not be re-issued. I don't like that option as it look rather weird and would keep target attached to control after `CloseTarget()` (though I don't see how this could cause problems).
2. Introduce some `LastTarget` private field and check it on re-attaching. If re-attaching to `LastTarget` then don't issue stored messages. I am more in favour of this solution, though it looks like a hack because of introducing some strange field.

**Comment by mikhail-barg** [comment]
Implemented option 2

**Comment by 304NotModified** [comment]
Sorry about the delay. Thanks for this nice pr!

**Comment by 304NotModified** [comment]
@mikhail-barg I renamed this PR. Is this a good summary for the release?

**Comment by mikhail-barg** [comment]
@304NotModified thank you for checking and improving it!

**Comment by 304NotModified** [comment]
oops forgot to release this

**Pull request merged**
